backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images

collections:
  - label: "Categories"
    label_singular: "Category"
    name: "categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
