backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images

collections:
  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
  - name: "author"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text" }
      - { name: "picture", label: "Picture", widget: "image", allow_multiple: false }
