backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images

collections:
  - name: "categories"
    identifier_field: "name"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
  - name: "authors"
    identifier_field: "name"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text" }
      - name: "picture"
        label: "Picture"
        widget: "image"
        allow_multiple: false
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - name: "date"
        label: "Publish Date"
        widget: "datetime"
        format: "MM-DD-YYYY"
        date_format: "MM-DD-YYYY"
        time_format: false
        picker_utc: true
      - name: "image"
        label: "Cover Image"
        widget: "object"
        fields:
          - { name: src, label: Image, widget: image, allow_multiple: false }
          - { name: alt, label: Alt text, widget: string }
      - name: "author"
        label: "Author"
        widget: "relation"
        collection: "authors"
        value_field: "slug"
        search_fields: ["name"]
      - name: "categories"
        label: "Categories"
        widget: "relation"
        collection: "categories"
        value_field: "slug"
        search_fields: ["name"]
        multiple: true
      - { name: "body", label: "Body", widget: "markdown" }
